# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "40e8562d283c992117cad3235b69449c"
name = "Sitejojo Bundle app"
handle = "sitejojo-bundle-app-3"
application_url = "https://ecommerce-wrap-boys-retirement.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-store-123644.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_cart_transforms,write_order_edits,write_products"

[auth]
redirect_urls = [
  "https://ecommerce-wrap-boys-retirement.trycloudflare.com/auth/callback",
  "https://ecommerce-wrap-boys-retirement.trycloudflare.com/auth/shopify/callback",
  "https://ecommerce-wrap-boys-retirement.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://casinos-hospitals-finance-follows.trycloudflare.com/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false
